version: '3.7'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - "5775:5775"   # Agent
      - "6831:6831"   # Thrift
      - "6832:6832"   # Thrift
      - "5778:5778"   # HTTP
      - "16686:16686" # Jaeger UI
      - "14250:14250" # gRPC
      - "14268:14268" # HTTP collector
      - "14250:14250" # gRPC collector
    networks:
      - jaeger_network

networks:
  jaeger_network:
    driver: bridge
